backend:
  name: github
  repo: tonymamo/getpackup
  api_root: https://api.github.com
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    editor:
      preview: false
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: Title, name: title, widget: string }
      - { label: "Publish Date", name: date, widget: datetime }
      - { label: Description, name: description, widget: text }
      - { label: "Featured Post", name: featuredpost, widget: boolean }
      - { label: "Featured Image", name: featuredimage, widget: image }
      - { label: Body, name: body, widget: markdown }
      - { label: Tags, name: tags, widget: list }

  - name: "pages"
    label: "Pages"
    editor:
      preview: false
    files:
      - file: "src/pages/index.md"
        label: "Home Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: HeroImage, name: heroImage, widget: image }
          - { label: HeroHeading, name: heroHeading, widget: string }
          - {
              label: HeroHeadingTypewriter,
              name: typewriterList,
              widget: list,
              fields: [{ label: text, name: text, widget: string }],
            }
          - { label: HeroSubheading, name: heroSubheading, widget: string }
          - { label: HeroCTALink, name: heroCTALink, widget: string }
          - { label: HeroCTAText, name: heroCTAText, widget: string }
          - {
              label: Mainpitch,
              name: mainpitch,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  {
                    label: Cards,
                    name: cards,
                    widget: list,
                    fields:
                      [
                        { label: Title, name: title, widget: string },
                        { label: Text, name: text, widget: text },
                        {
                          label: Image,
                          name: image,
                          widget: image,
                          required: false,
                        },
                        {
                          label: Icon,
                          name: icon,
                          widget: image,
                          required: false,
                        },
                        { label: Link, name: link, widget: string },
                        { label: LinkText, name: linkText, widget: string },
                        {
                          label: LinkType,
                          name: linkType,
                          widget: select,
                          options: ["button", "link"],
                        },
                      ],
                  },
                ],
            }
          - {
              label: SecondPitch,
              name: secondpitch,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Text, name: text, widget: text },
                  { label: Caption, name: caption, widget: string },
                  { label: Image, name: image, widget: image, required: false },
                  { label: Link, name: link, widget: string },
                  { label: LinkText, name: linkText, widget: string },
                  {
                    label: LinkType,
                    name: linkType,
                    widget: select,
                    options: ["button", "link"],
                  },
                ],
            }
          - {
              label: ThirdPitch,
              name: thirdpitch,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Text, name: text, widget: text },
                  { label: Caption, name: caption, widget: string },
                  { label: Image, name: image, widget: image, required: false },
                  { label: Link, name: link, widget: string },
                  { label: LinkText, name: linkText, widget: string },
                  {
                    label: LinkType,
                    name: linkType,
                    widget: select,
                    options: ["button", "link"],
                  },
                ],
            }
      - file: "src/pages/landing.md"
        label: "Landing Page"
        name: "landing"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "landing-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: "Hero Image", name: heroImage, widget: image }
          - { label: "Hero Heading", name: heroHeading, widget: string }
          - { label: "Hero Subheading", name: heroSubheading, widget: string }
          - {
              label: Consumer,
              name: consumer,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Body, name: body, widget: markdown },
                  { label: CTA, name: cta, widget: string },
                  { label: Icon, name: icon, widget: image },
                ],
            }
          - {
              label: Agent,
              name: agent,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Body, name: body, widget: markdown },
                  { label: CTA, name: cta, widget: string },
                  { label: Icon, name: icon, widget: image },
                ],
            }
          - {
              label: Mainpitch,
              name: mainpitch,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  {
                    label: Steps,
                    name: steps,
                    widget: list,
                    fields:
                      [
                        { label: Title, name: title, widget: string },
                        { label: Text, name: body, widget: markdown },
                        { label: Image, name: image, widget: image },
                      ],
                  },
                ],
            }
          - {
              label: SecondPitch,
              name: secondpitch,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Text, name: body, widget: markdown },
                  { label: Image, name: image, widget: image },
                  { label: Link, name: link, widget: string },
                  { label: LinkText, name: linkText, widget: string },
                ],
            }
      - file: "src/pages/frequently-asked-questions.md"
        label: "FAQ Page"
        name: "frequently-asked-questions"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "frequently-asked-questions",
            }
          - { label: Title, name: title, widget: string }
          - { label: "Hero Image", name: heroImage, widget: image }
          - { label: "Hero Heading", name: heroHeading, widget: string }
          - { label: "Hero Subheading", name: heroSubheading, widget: string }
          - {
              label: "Consumer FAQ",
              name: consumerFaq,
              widget: object,
              fields:
                [
                  {
                    label: "FAQ Item",
                    name: items,
                    widget: list,
                    fields:
                      [
                        { label: Question, name: question, widget: string },
                        { label: Answer, name: answer, widget: markdown },
                      ],
                  },
                ],
            }
          - {
              label: "Agent FAQ",
              name: agentFaq,
              widget: object,
              fields:
                [
                  {
                    label: "FAQ Item",
                    name: items,
                    widget: list,
                    fields:
                      [
                        { label: Question, name: question, widget: string },
                        { label: Answer, name: answer, widget: markdown },
                      ],
                  },
                ],
            }
      - file: "src/pages/about.md"
        label: "About"
        name: "about"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
      - file: "src/pages/terms.md"
        label: "Terms"
        name: "terms"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "terms",
            }
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
      - file: "src/pages/privacy.md"
        label: "Privacy"
        name: "privacy"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "privacy",
            }
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
