export type ActivityTypes = {
  airplane: boolean;
  baby: boolean;
  backcountryThreeSeason: boolean;
  backcountryWinter: boolean;
  basicHut: boolean;
  bikepacking: boolean;
  biking: boolean;
  bivy: boolean;
  boat: boolean;
  bouldering: boolean;
  bus: boolean;
  car: boolean;
  carCamp: boolean;
  carCamping: boolean;
  casual: boolean;
  crossCountrySkiing: boolean;
  dayTrip: boolean;
  essential: boolean;
  fishing: boolean;
  hiking: boolean;
  hostel: boolean;
  hotel: boolean;
  iceClimbing: boolean;
  international: boolean;
  kids: boolean;
  motorcycle: boolean;
  mountainBiking: boolean;
  multidayTrip: boolean;
  paddling: boolean;
  pets: boolean;
  photography: boolean;
  resort: boolean;
  resortSkiing: boolean;
  servicedHut: boolean;
  skiTouring: boolean;
  snowboarding: boolean;
  snowshoeing: boolean;
  sportClimbing: boolean;
  tent: boolean;
  touring: boolean;
  tradClimbing: boolean;
  trailRunning: boolean;
  train: boolean;
};

export type GearItemType = {
  id: string;
  name: string;
  category: string;
  lastEditedBy?: string;
  created: firebase.firestore.Timestamp;
  updated?: firebase.firestore.Timestamp;
  essential: boolean;
  isCustomGearItem?: boolean;
} & ActivityTypes;

export type GearListEnumType = Array<{
  name: keyof ActivityTypes;
  label: string;
  icon: string;
}>;
